### PR TITLE
Added instructions and schema to use or migrate to SQLite

### PR DESCRIPTION
**Pull request by akpu1**
~~- makes SQLite 3 the default database engine~~ (contentious, so i separated from this PR)
- adds SQLite schema in addition to MySQL one
- readme now includes instructions on how to setup SQLite DB
- readme now includes migration instructions

See discussion at #11

### CODE REVIEW

**Comment by alucard0134** [comment]
what i would do for the migration is to just create a bash script for it, and perhaps we can have make generate a sqlite db as well? albeit it can leave an unwanted file

**Comment by akpu1** [comment]
@alucard0134 that's what i had initially (bash script), but thought it made the process look too complicated :P 

The make thing is a good idea actually, I'll add that.

```bash
MYSQL_USER=user
MYSQL_PASS=pass
WEB_USER=nginx
# below options are unlikely to need to be changed
MYSQL_DB=pomf
SQLITE_DIR=/var/db/pomf
SQLITE_FILE=pomf.sq3
WORKING_DIR=/tmp

mkdir $SQLITE_DIR
wget -O ${WORKING_DIR}/m2s https://github.com/dumblob/mysql2sqlite/raw/master/mysql2sqlite.sh
mysqldump -u $MYSQL_USER -p $MYSQL_PASS $MYSQL_DB | sh /tmp/m2s > ${SQLITE_DIR}/initial_dump.sql
 sqlite3 ${SQLITE_DIR}/${SQLITE_FILE} -init ${SQLITE_DIR}/initial_dump.sql

rm ${WORKING_DIR}/m2s
chown -R ${WEB_USER}:${WEB_USER} $SQLITE_DIR
chmod 0750 $SQLITE_DIR
chmod 0640 ${SQLITE_DIR}/${SQLITE_FILE}

echo == SQLite DB at ${SQLITE_DIR}/${SQLITE_FILE} prepared from MySQL dump ==
echo == The dump used has been saved at ${SQLITE_DIR}/initial_dump.sql ==
```

**Comment by alucard0134** [comment]
have it be curl/wget from ghostbin/raw and then tell them to edit the variables, shouldn't be rocket science

**Comment by alucard0134** [comment]
also i would prefer instead of using nil variables is to have an if else statement in the database connecting using POMF_DB_TYPE

thoughts @ewhal

**Comment by akpu1** [comment]
@alucard0134 pls read relevant PDO docs before making comments like that
http://php.net/manual/en/pdo.construct.php

the parameter is ignored for SQLite, having a value in it make no difference, so an if else statement is silly IMO

The null thing, btw, was so that there aren't random useless credentials in the configuration file, rather than some necessity to use SQLite through PDO.

**Comment by ewhal** [comment]
I think it's fine to merge. We will be relocating the instructions to the documentation in the future.

**Pull request merged**
