### PR TITLE
Use SQLite as default DB; added migration instructions

### PR DESCRIPTION
**Pull request by akpu1**
- makes SQLite default database in settings.inc.php
- adds SQLite schema in addition to mysql one
- readme now includes instructions on how to setup sqlite DB
- readme includes migration instructions

### CODE REVIEW

**Comment by akpu1** [comment]
don't merge yet pls

**Comment by lesderid** [comment]
Don't put data that changes in /usr. See http://www.pathname.com/fhs/pub/fhs-2.3.html#PURPOSE18.

It should probably be somewhere in /var.

**Comment by alucard0134** [comment]
that and there should be a much simplier way of migration, and a simplier configuration change too thats semi-less ghetto

**Comment by akpu1** [comment]
@alucard0134 see new PR; migration is a little bit simpler.

The migration process is really incredibly simple ultimately, and is basically three commands plus changing the DSN.

mysql dump | convert | sqlite; and change the DSN (i don't really see an issue with that part, so please explain)

**Pull request closed without merging**
